mybean:
  name: App

#my.servers[0]=dev.example.com
#my.servers[1]=another.example.com
#
#my.servers0=dev.example.com
#my.servers1=another.example.com
my:
  servers:
    - dev.example.com
    - another.example.com


acme:
    remote-address: 192.168.1.1
    security:
        username: admin
        password: admincss
        roles:
            - USER
            - ADMIN
